Installing nginxon the server

diff --git a/0x0C-web_server/1-install_nginx_web_server b/0x0C-web_server/1-install_nginx_web_server
--- a/0x0C-web_server/1-install_nginx_web_server
+++ b/0x0C-web_server/1-install_nginx_web_server
@@ -1,23 +1,36 @@
 #!/usr/bin/env bash
 # This scipt install Nginx on a web server
 
- # Update package list
-  apt-get update
+# Updating the package and install Nginx
+sudo apt update
+sudo apt install -y nginx
 
- # Install Nginx
-  apt-get -y install nginx
+# Checing if Nginx is installed successfully
+if ! [ -x "$(command -v nginx)" ]; then
+  echo "Error: Nginx installation failed. Exiting."
+  exit 1
+fi
 
- # Configure Nginx
-  cat > /etc/nginx/sites-available/default << EOL
-  server {
-      listen 80;
-      web-01;
+# Configuring Nginx to listen on port 80 and return "Hello World!".
+cat <<EOF | sudo tee /etc/nginx/sites-available/default
+server {
+    listen 80;
+    server_name _;
 
-      location / {
-          return 200 "Hello World";
-      }
- }
- EOL
+    location / {
+        return 200 "Hello World!";
+    }
+}
+EOF
 
- # Restart nginx
-  service nginx restart
+# Restart Nginx
+sudo service nginx restart
+
+# Check if Nginx is running and listening on port 80
+if ! sudo lsof -i :80 | grep LISTEN; then
+  echo "Error: Nginx is not running or not listening on port 80. Please check the configuration."
+  exit 1
+fi
+
+echo "Nginx has been installed and configured successfully."
+
